version: "3.9"

services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    restart: always

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
